[theme]
primaryColor = "#234d3c"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"
font = "serif"

[server]
maxUploadSize = 10

[browser]
gatherUsageStats = false
